name: check

on:
  - push
  - pull_request

permissions:
  contents: read

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5.0.0

      - name: Install Nix
        uses: cachix/install-nix-action@v31.9.0

      - name: Install dependencies
        run: nix develop --command bun install
        working-directory: frontend

      - name: Run linter
        run: nix develop --command bun run lint
        working-directory: frontend

      - name: Run formatter
        run: nix develop --command bun run format
        working-directory: frontend
